### PR TITLE
feat: rename cache task to persistent cache task

### PR DESCRIPTION
**Pull request by gaius-qi**

### CODE REVIEW

**Review by CormickKneey — APPROVED** [review]
lgtm

**Comment by yxxhero** [comment]
@gaius-qi  please fix CI issue.   


This pull request includes several changes to the `dragonfly-client-storage` and `dragonfly-client-backend` modules, focusing on renaming cache task-related structures and methods to emphasize persistence. The most important changes include updating dependencies, renaming structs and methods for clarity, and modifying metadata management.

### Dependency Updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated `dragonfly-api` dependency from version `2.0.159` to `2.0.162`.

### Renaming for Clarity:
* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL49-R54): Renamed `WriteCacheTaskResponse` to `WritePersistentCacheTaskResponse` and updated associated methods to reflect the persistent nature of tasks. [[1]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL49-R54) [[2]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL329-R333) [[3]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL346-R346) [[4]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL357-R360) [[5]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL382-R388) [[6]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL423-R437)
* [`dragonfly-client-storage/src/lib.rs`](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL154-R175): Renamed various methods in the `Storage` implementation to reflect the persistent nature of cache tasks. [[1]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL154-R175) [[2]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL184-R184) [[3]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL193-R251)
* [`dragonfly-client-storage/src/metadata.rs`](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L131-R145): Renamed `CacheTask` struct to `PersistentCacheTask` and updated related methods and documentation. [[1]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L131-R145) [[2]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L174-R210) [[3]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L219-R229) [[4]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L320-R320) [[5]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L536-R548) [[6]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L565-R584) [[7]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L600-R608) [[8]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L622-R625)

**Comment by gaius-qi** [comment]
This pull request includes updates to the `dragonfly-client-storage` module, focusing on renaming and updating the terminology from "cache task" to "persistent cache task" to better reflect the functionality. Additionally, it includes a version update for the `dragonfly-api` dependency.

Dependency Update:

* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L33-R33): Updated the version of `dragonfly-api` from `2.0.159` to `2.0.162`.

Terminology and Struct Renaming:

* [`dragonfly-client-storage/src/content.rs`](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL49-R54): Renamed `WriteCacheTaskResponse` to `WritePersistentCacheTaskResponse` and updated related method names and comments to use "persistent cache task". [[1]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL49-R54) [[2]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL329-R333) [[3]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL346-R346) [[4]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL357-R360) [[5]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL382-R388) [[6]](diffhunk://#diff-2c03376b0ad153d44b0f6af6709c05dc4d1ff5e1f00dc9bccc34611868d2f6cdL423-R440)
* [`dragonfly-client-storage/src/lib.rs`](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL154-R177): Updated method names and comments in the `Storage` implementation to reflect the change to "persistent cache task". [[1]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL154-R177) [[2]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL184-R186) [[3]](diffhunk://#diff-09bca31ba146d9bc116819606a37c3f4073946a1e2af40382b3c41e440869e6eL193-R269)
* [`dragonfly-client-storage/src/metadata.rs`](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L131-R145): Renamed `CacheTask` to `PersistentCacheTask` and updated associated methods and comments. [[1]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L131-R145) [[2]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L174-R210) [[3]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L219-R229) [[4]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L320-R320) [[5]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L536-R548) [[6]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L565-R584) [[7]](diffhunk://#diff-58e1a6463adbab70df687ead673404e28a954e0a3e955683356e63eda00dcfe9L600-R608)

**Review by yxxhero — APPROVED** [review]

**Review by chlins — DISMISSED** [review]
lgtm

**Review by yxxhero — APPROVED** [review]
/LGTM

**Pull request merged**
